//Describe lo que sucede en la app

export const GUARDAR_DATOS_PERSONA = 'GUARDAR_DATOS_PERSONA';
export const GUARDAR_DATOS_PERSONA_OK = 'GUARDAR_DATOS_PERSONA_OK';
export const GUARDAR_DATOS_PERSONA_ERROR = 'GUARDAR_DATOS_PERSONA_ERROR';

export const COMENZAR_DESCARGA_DATOS = 'COMENZAR_DESCARGA_DATOS';
export const DESCARGA_DATOS_OK = 'DESCARGA_DATOS_OK';
export const DESCARGA_DATOS_ERROR = 'DESCARGA_DATOS_ERROR';

